version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_VERSION: "0.10.1.0"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  localstack:
    image: localstack/localstack:0.10.5
    ports:
      - "4567-4599:4567-4599"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
